### ISSUE TITLE
openStream presumes it's a file

### ISSUE THREAD

**Issue by sfescape** [ZJONSSON/parquetjs#22]
openStream calls osclose which presumes a close function on the stream.

**Comment by sfescape** [comment]
I'll have a look (I don't use github so I'll need to step through the process). I'm trying to figure out which project to use, this one seems most up to date and parquet-tools reads the output files fine, but dremio errors out.

This project: https://github.com/kbajalc/parquets

Dremio can read the files written using that project, but the project doesn't handle optional fields correctly. So I need to decide should I work with Dremio on figuring out why they can't read the files written using this project, or figure out how to fix kbajalc's version for optional fields.

The ironSource project itself doesn't seem to be very active.

Meanwhile, none of the available options actually works for me as the destination for the parquet files I'm writing is dremio.

**Comment by ZJONSSON** [comment]
Looking at this more closely you should be able to use the `ParquetTransformer` which basically returns a native `Transform` stream that can be piped into any writable stream.   You pipe the data into the ParquetTransformer and out comes the parquetFile as a stream.

Example: https://github.com/ZJONSSON/parquetjs/blob/master/test/integration.js#L436-L446

**Comment by sfescape** [comment]
Ahh, I'll have a look at ParquetTransformer also. The osclose patch is easy enough.

**Comment by sfescape** [comment]
I notice that snippet uses the schema level compression option, you seem to have removed that option from the code though. When I add schema level compression it doesn't do anything, only column level compression works.

**Comment by ZJONSSON** [comment]
I think the standard only defines compression on a column by column basis.  Not sure what the global compression was supposed to do (if anything).   Maybe either remove from test code or try to figure out how it was supposed to work.

**Comment by sfescape** [comment]
The global compression changed the default column compression from 'UNCOMPRESSED'.
