### ISSUE TITLE
Updating README.md with proper installation command

### ISSUE THREAD

**Issue by mytusshar** [ZJONSSON/parquetjs#32]
I found one issue in README.md file. It shows `npm install parquetjs` command for installation. But when I use it, I got issue with accessing openS3 method. I think, documentation need to be updated with this information.
This is my first time contributing to open-source community. Let me know, should I change it or not.

**Comment by ZJONSSON** [comment]
Awesome @mytusshar thanks for the contribution.   To get this merged you would need to do create a pull request, from your master (or branch) into zjonsson/parquetjs

I went a head and created a PR which I will be merging.  Thanks again and please share any improvements that you can think of.

![image](https://user-images.githubusercontent.com/1082488/59854563-271ed480-9341-11e9-85df-b9463cb92913.png)
