### ISSUE TITLE
Adding a new data to existing parquet file

### ISSUE THREAD

**Issue by MetinArslanturk** [ZJONSSON/parquetjs#36]
Hello,
You described it in here : https://github.com/ironSource/parquetjs/issues/82#issuecomment-481759082

But when i try to add new data to existing data it failed. Can you give a little detailed explanation or demo code please? 
Thanks from now.

**Comment by ZJONSSON** [comment]
This is a relatively advanced topic and I do not have any examples.  Basically you would read the metadata and then copy the file from the first byte to the last byte referenced in the metadata.  Then you would use the writer to add data and close the file by writing the new metadata (i.e. original + the data you just appended).   I'll definitely keep in mind to add some advanced demo examples in the future
