### ISSUE TITLE
Any way to also upload the parquet file on S3

### ISSUE THREAD

**Issue by staronline1985** [ZJONSSON/parquetjs#40]
Actually below is the scenario , I  am reading data from none sql database and then convert into parquet file and upload on S3 . During file conversion i don't want to store file in memory or local store . so is any way i will pass the stream and s3 and parquet schema . It will automatically upload on S3.

**Comment by ZJONSSON** [comment]
Yes, you can write to a generic stream that you can pass on to S3.  

Roughly:

```js
const Body = stream.Transform();
var writer = await parquet.ParquetWriter.openStream(schema, Body);
const uploadPromise = s3Client.upload({Bucket, Key, Body}).promise();

/// then write stuff here, close at the end
```

**Comment by staronline1985** [comment]
Thanks for response. I am getting below error . Can you please suggest me what i am doing wrong. 

Below is the code. 

 let writeableStream = new stream.Writable();
    let buffer = Buffer.from('');
    writeableStream._write = (chunk, encoding, done) => {
        buffer = Buffer.concat([buffer, chunk]);
        done();
    };
    writeableStream.close = e => e(); // pass in an error if there was one
   
    let parquetSchema = await convertJsonSchemaToParquetSchema(jsonSchema);

    var parquetTransform = new parquet.ParquetTransformer(parquetSchema);
    // pipe to connect the read, transform, and write streams
    readableStream.pipe(parquetTransform).pipe(writeableStream);

Below are the exception log.
TypeError: Cannot read property 'fieldList' of undefined
      at Object.exports.shredRecord (node_modules/parquetjs-lite/lib/shred.js:31:28)
      at ParquetWriter.appendRow (/node_modules/parquetjs-lite/lib/writer.js:94:22)
      at ParquetTransformer._transform (/node_modules/parquetjs-lite/lib/writer.js:306:19)
      at ParquetTransformer.Transform._read (_stream_transform.js:190:10)
      at ParquetTransformer.Transform._write (_stream_transform.js:178:12)
      at doWrite (_stream_writable.js:415:12)
      at writeOrBuffer (_stream_writable.js:399:5)
      at ParquetTransformer.Writable.write (_stream_writable.js:299:11)
      at Cursor.ondata (_stream_readable.js:708:20)
      at Cursor.emit (events.js:198:13)
      at Cursor.EventEmitter.emit (domain.js:448:20)
      at addChunk (_stream_readable.js:287:12)
      at readableAddChunk (_stream_readable.js:268:11)
      at Cursor.Readable.push (_stream_readable.js:223:10)

**Comment by staronline1985** [comment]
Thanks for kind response. I am trying  like this but getting issue. I am beginner to use this. 
let readableStream=dbo.collection(collectionName).find(query);
itemsStream = cursor.stream();
   let buffer = Buffer.from('');
    writeableStream._write = (chunk, encoding, done) => {
        console.log(chunk);
        buffer = Buffer.concat([buffer, chunk]);
        done();
    };
    writeableStream.close = e => e(); // pass in an error if there was one
      let parquetSchema = await convertJsonSchemaToParquetSchema(jsonSchema);
    var parquetTransform = new parquet.ParquetTransformer(parquetSchema);
    // pipe or use pump to connect the read, transform, and write streams
    readableStream.pipe(parquetTransform).pipe(writeableStream);
    let result = await fileuploader.UploadFile(writeableStream, "serverless");

**Comment by ZJONSSON** [comment]
I can only provide generic guidance on this library, for more detailed help you should study node streams in detail and post questions on stackoverflow.com
